# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# auto: true
# server: true

# markdown: kramdown
highlighter: rouge

# highlighter: pygments

theme: jekyll-theme-slate
google_analytics: UA-50817371-1
