# markdown: redcarpet
# redcarpet:
#     extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
# auto: true
# server: true
# markdown: kramdown
# highlighter: pygments

highlighter: rouge

theme: jekyll-theme-slate
google_analytics: UA-50817371-1

marked:
    # gfm: true
    breaks: false
